### ISSUE TITLE
"thunderbird-donate" can't be checked by the pipeline bot

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-cron#29]
"""
Error: This app (thunderbird-donate-staging) does not seem to be a part of any pipeline
"""

It's probably because "thunderbird" is a different team.

**Comment by patjouk** [comment]
While I'm there, I should also fix the link to the donate pipeline because it's broken :(

**Comment by cadecairos** [comment]
Not sure this is worth the time and effort.
